baseURL = 'http://tanimpavel.com/'
languageCode = 'en-us'
title = 'Tanim Pavel'
theme = 'm10c'
avatar = 'avatar.jpg'

[permalinks]
  posts = '/:title/'

[params]
  author = "Tanim Pavel"
  description = " "
  menu_item_separator = " - "
  

  # Green theme
  [params.style]
  darkestColor = "#1ea682"
  darkColor = "#212121"
  lightColor = "#ffffff"
  lightestColor = "#ffffff"
  primaryColor = "#ffffff"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = -110
  
  [[menu.main]]
    identifier = 'about'
    name = 'About'
    url = '/about'
    weight = -100

